// Generated by Wrangler on Thu Jun 06 2024 22:09:04 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	KV_NAMESPACE: KVNamespace;
	PASSWORD: string;
	BUCKET: R2Bucket;
}
