#:schema node_modules/wrangler/config-schema.json
name = "flare-bin"
main = "src/index.ts"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]

# Uncomment to use a custom domain.
# route = { pattern = "example.com", custom_domain = true }
# workers_dev = false

[[kv_namespaces]]
binding = "KV_NAMESPACE"
id = "" # Fill your KV namespace ID.

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "" # Fill your bucket name.

[triggers]
crons = ["0 * * * *"]
